// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddUserRequest struct {
	UserName  string `json:"username"`
	PassWord  string `json:"password"`
	Gender    int    `json:"gender"`
	Email     string `json:"email"`
	Telephone string `json:"telephone"`
	Age       int    `json:"age"`
}

type DeleteUserRequest struct {
	Id int `json:"id"`
}

type GetUserInfoRequest struct {
	Id int `json:"id"`
}

type GetUserListPageData struct {
	Id        int    `json:"id"`
	UserName  string `json:"username"`
	PassWord  string `json:"password"`
	Gender    int    `json:"gender"`
	Email     string `json:"email"`
	Telephone string `json:"telephone"`
	Age       int    `json:"age"`
}

type GetUserListPageRequest struct {
	PageSize    int    `json:"pagesize"`
	CurrentPage int    `json："currentpage"`
	UserName    string `json:"username"`
}

type GetUserListPageResponse struct {
	Data []GetUserListPageData `json:"data"`
}

type UpdateUserRequest struct {
	Id        int    `json:"id"`
	UserName  string `json:"username"`
	PassWord  string `json:"password"`
	Gender    int    `json:"gender"`
	Email     string `json:"email"`
	Telephone string `json:"telephone"`
	Age       int    `json:"age"`
}

type UserAddResponse struct {
	Code int `json:"code"`
}

type UserLoginRequest struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}
